remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: My GitHub Pages Site
description: Guides, electronics projects, and repair tips
url: "https://pexers.github.io"
baseurl: ""
github_username: Pexers

collections:
  cards:
    output: true
    permalink: /projects/:name/
  menus:
    output: true
    permalink: /:name/
